#!/usr/bin/env python3
"""Generate firmware/sdkconfig.local from wifi.local.txt plus arguments.

The password lives in wifi.local.txt (gitignored) and is copied straight into the generated
sdkconfig fragment (also gitignored). Neither file is ever printed, so the password does not
end up in a build log or a terminal scrollback.

Usage:
    python scripts/gen_local_config.py --ssid "deco m9" --server 192.168.0.100 [--bssid aa:bb:...]
"""

import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent


def read_password(path: pathlib.Path) -> str:
    if not path.exists():
        sys.exit(f"{path} does not exist — create it with a PASSWORD= line")
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("PASSWORD="):
            return line[len("PASSWORD=") :].strip()
    sys.exit(f"{path} has no PASSWORD= line")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ssid", required=True)
    parser.add_argument("--server", required=True, help="Server IPv4 address")
    parser.add_argument("--bssid", default="", help="Lock to this BSSID; empty means do not lock")
    parser.add_argument("--node-id", type=int, default=1)
    parser.add_argument("--rate", type=int, default=100, help="Probe rate in Hz")
    parser.add_argument(
        "--probe",
        choices=("icmp", "udp"),
        default="icmp",
        help="icmp pings the gateway; udp bounces off the server's echo port, which is immune "
        "to a router that rate-limits ICMP. udp needs CSI_ECHO_PORT set on the server.",
    )
    parser.add_argument("--echo-port", type=int, default=5568)
    args = parser.parse_args()

    password = read_password(HERE / "wifi.local.txt")

    out = HERE / "sdkconfig.local"
    out.write_text(
        "\n".join(
            [
                "# Generated by scripts/gen_local_config.py. Contains the WiFi password;",
                "# gitignored, and not to be committed or pasted anywhere.",
                "CONFIG_CSI_ROLE_STATION=y",
                f"CONFIG_CSI_NODE_ID={args.node_id}",
                f'CONFIG_CSI_WIFI_SSID="{args.ssid}"',
                f'CONFIG_CSI_WIFI_PASSWORD="{password}"',
                f'CONFIG_CSI_LOCK_BSSID="{args.bssid}"',
                "CONFIG_CSI_SCAN_ON_BOOT=y",
                f'CONFIG_CSI_SERVER_HOST="{args.server}"',
                "CONFIG_CSI_SERVER_PORT=5566",
                (
                    "CONFIG_CSI_PROBE_ICMP=y"
                    if args.probe == "icmp"
                    else f"CONFIG_CSI_PROBE_UDP_ECHO=y\nCONFIG_CSI_ECHO_PORT={args.echo_port}"
                ),
                f"CONFIG_CSI_PROBE_RATE_HZ={args.rate}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    lock = args.bssid if args.bssid else "(none — will roam)"
    print(f"wrote {out}: ssid={args.ssid!r} server={args.server} node={args.node_id} "
          f"rate={args.rate}Hz probe={args.probe} lock={lock}")
    if args.probe == "udp":
        print(f"  the server needs CSI_ECHO_PORT={args.echo_port} set, or nothing will answer")


if __name__ == "__main__":
    main()
